---
version: 2

build:
  os: ubuntu-lts-latest
  tools:
    # Keep version in sync with tox.ini/docs and ci.yml/docs.
    python: "3.12"
  jobs:
    # Need the tags to calculate the version (sometimes).
    post_checkout:
      - git fetch --tags

    # Replace versions in sponsor URLs
    pre_build:
      - cog -rP docs/index.md

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
