---
version: 2
formats: all

build:
  os: ubuntu-20.04
  tools:
    # Keep version in sync with tox.ini/docs and ci.yml/docs.
    python: "3.10"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
