# SPDX-License-Identifier: MIT

[tox]
requires =
    tox>=4.51.0
    tox-uv
env_list =
    lint-{ruff,pre-commit},
    3.1{0-5}-tests,
    3.1{0-5}-mypy,
    pypy3.11-tests,
    # Mypy needs to run within the respective Python version
    typing-{pyright,ty,pyrefly}
    docs-{sponsors,doctests,build},
    changelog,
    coverage-{combine,report}


[pkgenv]
pass_env = SETUPTOOLS_SCM_PRETEND_VERSION


[testenv]
runner = uv-venv-lock-runner
package = wheel
wheel_build_env = .pkg
dependency_groups =
    tests: tests
    mypy: mypy
commands =
    tests: pytest {posargs:-n auto}
    mypy: pytest -k test_mypy
    mypy: mypy typing_tests
    mypy: mypy src/attrs/__init__.pyi src/attr/__init__.pyi src/attr/_typing_compat.pyi src/attr/_version_info.pyi src/attr/converters.pyi src/attr/exceptions.pyi src/attr/filters.pyi src/attr/setters.pyi src/attr/validators.pyi

[testenv:pypy3.11-tests]
dependency_groups = tests
commands = pytest tests/test_functional.py

[testenv:3.1{0,4}-tests]
dependency_groups = cov
# Python 3.6+ has a number of compile-time warnings on invalid string escapes.
# PYTHONWARNINGS=d makes them visible during the tox run.
set_env =
    COVERAGE_PROCESS_START={toxinidir}/pyproject.toml
    PYTHONWARNINGS=d
commands =
    coverage run -m pytest {posargs:-n auto}

# Split combine/report in 2 to avoid excessive "Combined data file ..." output.
[testenv:coverage-combine]
base_python_file = .python-version-default
depends = *-tests
package = skip
dependency_groups = cov
commands = coverage combine

[testenv:coverage-report]
base_python_file = .python-version-default
depends = coverage-combine
parallel_show_output = true
package = skip
dependency_groups = cov
commands = coverage report


[testenv:codspeed]
dependency_groups = benchmark
pass_env =
    CODSPEED_TOKEN
    CODSPEED_ENV
    ARCH
    PYTHONHASHSEED
    PYTHONMALLOC
commands = pytest --codspeed -n auto bench/test_benchmarks.py


[testenv:docs-{build,doctests,linkcheck}]
# Canonical version for everything documentation-related.
base_python = 3.14
dependency_groups = docs
commands =
    build: sphinx-build -n -T -W -b html -d {envtmpdir}/doctrees docs {posargs:docs/_build/}html
    doctests: sphinx-build -n -T -W -b doctest -d {envtmpdir}/doctrees docs {posargs:docs/_build/}html
    linkcheck: sphinx-build -W -b linkcheck -d {envtmpdir}/doctrees docs docs/_build/html

[testenv:docs-watch]
package = editable
base_python = {[testenv:docs-build]base_python}
dependency_groups = docs-watch
deps = watchfiles
commands =
    watchfiles \
        --ignore-paths docs/_build/ \
        'sphinx-build -W -n --jobs auto -b html -d {envtmpdir}/doctrees docs docs/_build/html' \
        README.md \
        src \
        docs

[testenv:docs-sponsors]
runner = uv-venv-runner
package = skip
description = Ensure sponsor logos are up to date.
deps = cogapp
commands = cog -rP README.md docs/index.md


[testenv:lint-{ruff,pre-commit}]
dependency_groups = lint
package = skip
commands =
    ruff: ruff check --fix --exit-non-zero-on-fix .
    ruff: ruff format --exit-non-zero-on-format .
    pre-commit: prek run --all-files


[testenv:changelog]
dependency_groups = docs
package = skip
commands =
    towncrier --version
    towncrier build --version main --draft


[testenv:typing-pyright]
dependency_groups = pyright
commands =
    pyright
    pytest tests/test_pyright.py -vv

[testenv:typing-ty]
dependency_groups = ty
commands = ty check typing_tests/baseline.py

[testenv:typing-pyrefly]
dependency_groups = pyrefly
commands = pyrefly check


[testenv:docset]
runner = uv-venv-runner
deps = doc2dash
dependency_groups = docs
allowlist_externals =
    rm
    cp
    tar
commands =
    rm -rf attrs.docset attrs.tgz docs/_build
    sphinx-build -n -T -W -b html -d {envtmpdir}/doctrees docs docs/_build/html
    doc2dash --index-page index.html --icon docs/_static/docset-icon.png --icon-2x docs/_static/docset-icon@2x.png  --online-redirect-url https://www.attrs.org/en/latest/ docs/_build/html
    tar --exclude='.DS_Store' -cvzf attrs.tgz attrs.docset
