from typing import List

class FrozenInstanceError(AttributeError):
    msg : str = ...
    args : List[str] = ...

class AttrsAttributeNotFoundError(ValueError): ...
class NotAnAttrsClassError(ValueError): ...
class DefaultAlreadySetError(RuntimeError): ...
