
class FrozenInstanceError(AttributeError):
    msg : str = ...
    args : tuple = ...

class AttrsAttributeNotFoundError(ValueError): ...
class NotAnAttrsClassError(ValueError): ...
class DefaultAlreadySetError(RuntimeError): ...
