from typing import Container, Iterable, List, Union
from . import _ValidatorType

def instance_of(type: type) -> _ValidatorType: ...
def provides(interface) -> _ValidatorType: ...
def optional(validator: Union[_ValidatorType, List[_ValidatorType]]) -> _ValidatorType: ...
def in_(options: Container) -> _ValidatorType: ...
def and_(*validators: Iterable[_ValidatorType]) -> _ValidatorType: ...
